fun foo(_f: Fun<(Int, Int)>) {}

// args: check
// expected exit status: 1
// expected stdout:
// Error: Fun takes 2 type arguments, but got 1 argument.
// 
// --> src/check_test_files/bad_fun_arity.gdn:1
// fun foo(_f: Fun<(Int, Int)>) {}
//                 ^^^^^^^^^^

